apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Values.appName }}
        app.kubernetes.io/name: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.nodeSelector | nindent 10 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{- toYaml .Values.tolerations | nindent 10 }}
{{- end }}
      containers:
{{- if .Values.image_override }}      
      - image: "{{ .Values.ecr }}.{{ .Values.region }}.amazonaws.com/{{ .Values.appName }}:{{ .Values.tag }}"
{{- else }}
      - image: "{{ .Values.image_override }}"
{{- end }}      
        envFrom:
          - configMapRef:
              name: {{ .Values.appName }}-config-map
          - secretRef:
              name: {{ .Values.appName }}-secrets
        name: {{ .Values.appName }}-server
        resources:
{{- toYaml .Values.resources | nindent 10 }}
