useStatefulSet: false
useCronJob: false
replicas: 1
namespace: default
CronJob:
  schedule: "0 * * * *"
ingresses: {}
serviceAccount:
  create: false
  name: "sa-name"
StatefulSet: {}
affinity: {}
nodeSelector: {}
tolerations: {}
livenessProbe: {}
readinessProbe: {}
secretConfigPointer: {}

firefly:
  clusterRole:
    states:
      create: false
    infrastructure:
      create: false
  role:
    create: false
  crd:
    Drifts:
      infrastructure:
        create: false
      states:
        create: false
    Integration:
      infrastructure:
        create: false
      states:
        create: false
    crawlers:
      create: false
    DeleteIntegration:
      infrastructure:
        create: false
      states:
        create: false
    Fetcher:
      create: false 
      maxReplicas: 10000
      resourceProfile: small6
    Crawler:
      create: false
  
# kubectl should be the same as cluster version
#kubectlVersion: "1.28.0"
restartPolicy: Always
autoReloadConfig: false
configmapName: ""
containers: {}
volumes: {}
PersistentVolumeClaim: {}
StorageClass: {}
volumeClaimTemplates: {}
securityContext: {} 
terminationGracePeriodSeconds: {}
volumeClaimTemplate: {}
secret:
  enabled: false
metricsService:
  enabled: false
serviceMonitor:
  enabled: false
service:
  customName: ""
  create: false
  type: NodePort
  servicePort: 7500
  targetPort: 80
clusterRoleBinding:
  customName: ""
clusterRole:
  customName: ""
  create: false
  rules:
    - apiGroups: ['batch']
      resources: ['jobs']
      verbs: ['get', 'list', 'watch', 'create', 'delete']
    # Add more rules as needed
role:
  create: false
  rules: {}
#auth0:
#  fireflyDomain: ""
#  providerDomain: ""
#elastic:
#  url: ""
#vault:
#  url: ""
customImage: {}
resources: {}
customLabels: {}
env: "test"
account: "1245"
domain: "domain"
tag: latest
region: us-west-2
image_override: busybox
ecr: 000000000000.dkr.ecr
deployment:
  customName: ""
appName: app-name
ecrAppName: ""

autoscaling:
  enabled: false 

keda:
  enabled: false
  queue: "queue"
  queueLength: 5
  config:
    minReplicaCount: 1
    maxReplicaCount: 100
    pollingInterval: 30
    cooldownPeriod: 300
    idleReplicaCount: 0
    fallback:
      failureThreshold: 10
      replicas: 1  
pdb:
  enabled: false
  minAvailable: 1
  maxUnavailable: 0
