useStatefulSet: true
replicas: 1
namespace: default

ingress:
  create: false
  schema: internal
  successcodes: 200,204
  healthcheckpath: /
  timeout: idle_timeout.timeout_seconds=180
#  cert: arn:aws:acm:us-west-2:000000000000:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  dns: 'app'
  waf:
    create: false
#    arn: 'arn:aws:wafv2:us-west-2:000000000000:regional/webacl/backend-waf/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'

serviceAccount:
  create: false
  name: "sa-name"

nodeSelector: {}
tolerations: {}
livenessProbe: {}

readinessProbe: {}


autoReloadConfig: false
configmapName: ""
containers: {}
PersistentVolumeClaim: {}
StorageClass: {}
volumeClaimTemplates: {}
securityContext: {} 
terminationGracePeriodSeconds: {}
volumeClaimTemplate: {}
secret:
  enabled: false
metricsService:
  enabled: false
serviceMonitor:
  enabled: false
  data:
    - honorLabels: true
      metricRelabelings:
        - action: labeldrop
          regex: false
      path: /metrics
      port: http
      relabelings:
        - action: labeldrop
          regex: false
service:
  create: false
  type: NodePort
  servicePort: 7500
  targetPort: 80

clusterRole:
  create: false

role:
  create: false
  rules: {}
#auth0:
#  fireflyDomain: ""
#  providerDomain: ""
#elastic:
#  url: ""
#vault:
#  url: ""
resources: {}

env: "test"
account: "1245"
domain: "domain"
tag: latest
region: us-west-2
image_override: busybox
ecr: 000000000000.dkr.ecr
appName: app-name
ecrAppName: ""

autoscaling:
  enabled: false 

keda:
  enabled: false
  queue: "queue"
  queueLength: 5
  config:
    minReplicaCount: 1
    maxReplicaCount: 100
    pollingInterval: 30
    cooldownPeriod: 300
    idleReplicaCount: 0
    fallback:
      failureThreshold: 10
      replicas: 1  
# Pod Affinity Configuration
podAffinity:
  preferred:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - my-app
        topologyKey: kubernetes.io/hostname
  required:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - my-app
        topologyKey: kubernetes.io/hostname

# Node Affinity Configuration
nodeAffinity:
  required:
    - matchExpressions:
        - key: node-role
          operator: In
          values:
            - my-node-role
  preferred:
    - matchExpressions:
        - key: zone
          operator: In
          values:
            - us-west1-a

pdb:
  enabled: false
  minAvailable: 1
  maxUnavailable: 0