{{- if .Values.firefly.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.appName }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.appName }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.appName }}-controller-manager
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.appName }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.appName }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.appName }}-controller-manager
    namespace: {{ .Values.namespace }}
{{- end }}