{{- if eq .Values.clusterRole.create true -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.appName }}
rules:
{{- range $index, $rule := .Values.clusterRole.rules }}
  - apiGroups:
{{- range $apiGroupIndex, $apiGroup := $rule.apiGroups }}
      {{ if eq $apiGroup "" }}- ''{{ else }}- {{ $apiGroup }}{{ end }}
{{- end }}
    resources:
{{ toYaml $rule.resources | indent 6 }}
    verbs:
{{ toYaml $rule.verbs | indent 6 }}
{{- end }}
{{- end }}
