{{- if eq .Values.clusterRole.create true -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.appName }}
rules:
  - apiGroups:
      - ''
      - "batch"
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
{{- end }}
