{{- range $index, $configMap := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMap.name }}
data:
  {{- (mergeOverwrite $configMap $.Values.tagsOverride ) | toYaml | nindent 2}}
{{- end }}