{{- if .Values.firefly.crd.Fetcher.create }}
apiVersion: infrastructure.gofirefly.io/v1beta1
kind: Fetcher
metadata:
  name: fetchers-prod-v1
  namespace: {{ .Values.appTemplate.namespace }}
spec:
  maxReplicas: {{ .Values.appTemplate.maxReplicas }}
  priorityQueue:
    url: "https://sqs.{{ .Values.appTemplate.region }}.amazonaws.com/{{ trimPrefix "_" .Values.appTemplate.account }}/{{ .Values.appTemplate.env }}-flywheel-fetchers-dispatcher-priority-sqs{{ .Values.appTemplate.cluster_suffix}}"
  queue:
    url: "https://sqs.{{ .Values.appTemplate.region }}.amazonaws.com/{{ trimPrefix "_" .Values.appTemplate.account }}/{{ .Values.appTemplate.env }}-flywheel-fetchers-dispatcher-sqs{{ .Values.appTemplate.cluster_suffix}}"
  resourceProfile: {{ .Values.appTemplate.resourceProfile }}
  roleARN: arn:aws:iam::{{ trimPrefix "_" .Values.appTemplate.account }}:role/{{ .Values.appTemplate.env }}-flywheel-producer-scheduler-oidc
{{- end }}