{{- if and .Values.useCronJob (not .Values.useStatefulSet) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  schedule: "{{ .Values.CronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            karpenter.sh/do-not-evict: 'true'
          labels:
            cron: {{ .Values.appName }}-cron
            app.kubernetes.io/instance: {{ .Values.appName }}
            app.kubernetes.io/name: {{ .Values.appName }}
        spec:
          {{- if .Values.serviceAccount.create }}
          serviceAccountName: {{ .Values.serviceAccount.name }}
          {{- end }}
          {{- if .Values.securityContext }}
          securityContext:
{{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.terminationGracePeriodSeconds }}
          terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds.seconds }}
          {{- end }}
          {{- if .Values.nodeSelector }}
          nodeSelector:
{{- toYaml .Values.nodeSelector | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
          {{- if .Values.tolerations }}
          tolerations:
            {{- range .Values.tolerations }}
            - effect: "{{ .effect }}"
              key: "{{ .key }}"
              operator: "{{ .operator }}"
              value: "{{ .value }}"
            {{- end }}
          {{- end }}
          {{- if .Values.affinity }}
          affinity:
{{- toYaml .Values.affinity | nindent 10 }}
          {{- end }} 
          containers:
          - image: "{{ trimPrefix "_" .Values.account }}.dkr.ecr.{{ .Values.region }}.amazonaws.com/{{ ne .Values.ecrAppName ""  | ternary .Values.ecrAppName .Values.appName }}:{{ .Values.tag }}"
            imagePullPolicy: {{ .Values.containers.imagePullPolicy }}
            {{- if .Values.containers.command }}
            command:
              {{- include "base.tplvalues.render" ( dict "value" .Values.containers.command "context" $ ) | nindent 10 }}
            {{- end }}
            {{- if .Values.containers.args }}
            args:
              {{- include "base.tplvalues.render" ( dict "value" .Values.containers.args "context" $ ) | nindent 10 }}
            {{- end }}
            {{- if .Values.containers.ports }}
            ports:
              {{- include "base.tplvalues.render" (dict "value" .Values.containers.ports "context" $) | nindent 10 }}
            {{- end }}
            {{- if .Values.containers.env }}
            env:
              {{- include "base.tplvalues.render" (dict "value" .Values.containers.env "context" $) | nindent 10 }}
            {{- end }}
            {{- if .Values.configMaps }}
            {{- if .Values.externalsecret }}
            envFrom:
            {{- range .Values.configMaps }}
              - configMapRef:
                  name: {{ .name }}
            {{- end }}
              - secretRef:
                  name: {{ .Values.externalsecret.targetname }}
            {{- else }}
            envFrom:
            {{- range .Values.configMaps }}
              - configMapRef:
                  name: {{ .name }}
            {{- end }}
            {{- end }}
            {{- else if .Values.externalsecret }}
            envFrom:
              - secretRef:
                  name: {{ .Values.externalsecret.targetname }}
            {{- end }}
            name: {{ .Values.appName }}
            resources:
{{- toYaml .Values.resources | nindent 14 }}
{{- end }}
