{{- if .Values.externalsecret -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}-external-secret
  namespace: {{ .Values.namespace }}
spec:
  data:
    {{- if .Values.externalsecret.values }}
    {{- include "base.tplvalues.render" ( dict "value" .Values.externalsecret.values "context" $ ) | nindent 4 }}
    {{- end }}
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.namespace }}.vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ .Values.externalsecret.targetname }}
{{- end }}