{{- range .Values.StorageClass }}
{{- if .create }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
provisioner: {{ .provisioner }}
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: {{ .type }}
  iops: {{ .iops }}
  throughput: {{ .throughput }}
reclaimPolicy: {{ .reclaimPolicy }}
allowVolumeExpansion: true
{{- end }}
{{- end }}