{{- if eq .Values.secret.create true -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-sa
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: kubernetes.io/service-account-token
{{- end }}