{{- if eq .Values.secret.enabled true -}}
{{- $name := .Chart.Name }}
{{- if .Values.fetcher }}
{{- $fetchTypes := splitList "," $.Values.fetcher.types }}
{{- $name = printf "%s-%s" $.Chart.Name (first $fetchTypes) }}
{{- else }}
{{- $name = printf "%s-iacathon" $.Chart.Name }}
{{- else }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-sa
  annotations:
    kubernetes.io/service-account.name: {{ $name }}
type: kubernetes.io/service-account-token
{{- end }}