{{- if eq .Values.service.create true -}}
---
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.customName }}
  name: {{ .Values.service.customName }}
{{- else }}
  name: {{ .Values.appName }}
{{- end }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.appName }}
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
{{- if .Values.customLabels }}
{{- range $key, $value := .Values.customLabels }}
    {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
    app.kubernetes.io/name: {{ .Values.appName }}
  type: {{ .Values.service.type }}
  sessionAffinity: None
{{- if eq .Values.service.type "NodePort" }}
  externalTrafficPolicy: Cluster
{{- end }}
{{- end }}