{{- if eq .Values.serviceAccount.create true -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  {{- if ne .Values.serviceAccount.role "" }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ trimPrefix "_" .Values.account }}:role/{{ .Values.env }}-{{ .Values.serviceAccount.role }}
  {{ end }}
{{- end }}