{{- if eq .Values.serviceMonitor.enabled true -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}-metrics
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
{{- toYaml .Values.serviceMonitor.data | nindent 4 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
{{- end }}
