{{- if eq .Values.serviceMonitor.enabled true -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/component: metrics
spec:
  endpoints:
{{- toYaml .Values.serviceMonitor.data | nindent 4 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
      app.kubernetes.io/component: metrics
{{- end }}
---
{{- if eq .Values.metricsService.enabled true -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/component: metrics
spec:
  ports:
    - port: {{ .Values.metricsService.servicePort }}
      targetPort: {{ .Values.metricsService.targetPort }}
      protocol: TCP
      name: {{ .Values.appName }}-metrics
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
{{- end }}
