{{- if eq .Values.serviceMonitor.enabled true -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}-metrics
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
    - honorLabels: true
      metricRelabelings:
        - action: labeldrop
          regex: {{ .Values.serviceMonitor.ignoreLabels }}
      path: /metrics
      port: http
      relabelings:
        - action: labeldrop
          regex: {{ .Values.serviceMonitor.ignoreLabels }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
{{- end }}
